#ifndef BIOME_WATER_SHADER_H
#define BIOME_WATER_SHADER_H

static const char *biomeWaterShaderSource =
    "struct Uniforms {\n"
    "  vp : mat4x4<f32>,\n"
    "  inv_vp : mat4x4<f32>,\n"
    "  light_vp : array<mat4x4<f32>, 4>,\n"
    "  cascade_splits : vec4<f32>,\n"
    "  light_ray_dir : vec4<f32>,\n"
    "  light_color : vec4<f32>,\n"
    "  camera_pos : vec4<f32>,\n"
    "  shadow_info : vec4<f32>,\n"
    "  ambient_light : vec4<f32>,\n"
    "  reserved_params : vec4<f32>,\n"
    "  tint_params : vec4<f32>,\n"
    "  time_params : vec4<f32>\n"
    "}\n"
    "@group(0) @binding(0) var<uniform> uniforms : Uniforms;\n"
    "@group(0) @binding(1) var ibl_prefiltered_env : texture_cube<f32>;\n"
    "@group(0) @binding(2) var ibl_sampler : sampler;\n"
    "@group(0) @binding(3) var opaque_scene : texture_2d<f32>;\n"
    "@group(0) @binding(4) var ibl_irradiance_env : texture_cube<f32>;\n"
    "struct GpuTransform {\n"
    "  c0 : vec4<f32>,\n"
    "  c1 : vec4<f32>,\n"
    "  c2 : vec4<f32>,\n"
    "  c3 : vec4<f32>\n"
    "}\n"
    "@group(3) @binding(0) var<storage, read> instance_transforms : array<GpuTransform>;\n"
    "@group(3) @binding(1) var<storage, read> instance_material_ids : array<u32>;\n"
    "struct VertexInput {\n"
    "  @location(0) pos : vec3<f32>,\n"
    "  @location(1) nrm : vec3<f32>,\n"
    "  @location(2) uv : vec2<f32>,\n"
    "  @location(3) tan : vec4<f32>,\n"
    "  @location(4) slot : u32\n"
    "}\n"
    "struct VertexOutput {\n"
    "  @builtin(position) pos : vec4<f32>,\n"
    "  @location(0) world_pos : vec3<f32>,\n"
    "  @location(1) normal : vec3<f32>,\n"
    "  @location(2) terrain_depth : f32,\n"
    "  @location(3) frozen : f32\n"
    "}\n"
    "@vertex fn vs_main(input : VertexInput) -> VertexOutput {\n"
    "  let t = instance_transforms[input.slot];\n"
    "  let model = mat4x4<f32>(\n"
    "    vec4<f32>(t.c0.xyz, 0.0),\n"
    "    vec4<f32>(t.c1.xyz, 0.0),\n"
    "    vec4<f32>(t.c2.xyz, 0.0),\n"
    "    vec4<f32>(t.c3.xyz, 1.0));\n"
    "  let world = model * vec4<f32>(input.pos, 1.0);\n"
    "  let normal_matrix = mat3x3<f32>(\n"
    "    cross(t.c1.xyz, t.c2.xyz),\n"
    "    cross(t.c2.xyz, t.c0.xyz),\n"
    "    cross(t.c0.xyz, t.c1.xyz));\n"
    "  var out : VertexOutput;\n"
    "  out.pos = uniforms.vp * world;\n"
    "  out.world_pos = world.xyz;\n"
    "  out.normal = normalize(normal_matrix * input.nrm);\n"
    "  out.terrain_depth = input.uv.x;\n"
    "  out.frozen = input.uv.y;\n"
    "  return out;\n"
    "}\n"
    "fn wave_slope(\n"
    "  p : vec2<f32>,\n"
    "  direction : vec2<f32>,\n"
    "  frequency : f32,\n"
    "  amplitude : f32,\n"
    "  speed : f32,\n"
    "  time : f32) -> vec2<f32> {\n"
    "  let phase = dot(p, direction) * frequency + time * speed;\n"
    "  return direction * cos(phase) * amplitude * frequency;\n"
    "}\n"
    "fn fresnel_schlick(cos_theta : f32) -> f32 {\n"
    "  let x = 1.0 - clamp(cos_theta, 0.0, 1.0);\n"
    "  return 0.02037 + (1.0 - 0.02037) * x * x * x * x * x;\n"
    "}\n"
    "@fragment fn fs_main(input : VertexOutput) -> @location(0) vec4<f32> {\n"
    "  let p = input.world_pos.xz;\n"
    "  let time = uniforms.time_params.x;\n"
    "  let frozen = clamp(input.frozen, 0.0, 1.0);\n"
    "  var slope = wave_slope(p, normalize(vec2<f32>(1.0, 0.32)), 0.16, 0.18, 0.75, time);\n"
    "  slope += wave_slope(p, normalize(vec2<f32>(-0.38, 1.0)), 0.31, 0.09, 1.15, time);\n"
    "  slope += wave_slope(p, normalize(vec2<f32>(0.72, -1.0)), 0.62, 0.035, 1.8, time);\n"
    "  slope += wave_slope(p, normalize(vec2<f32>(-1.0, -0.68)), 1.17, 0.012, 2.55, time);\n"
    "  slope *= 1.0 - frozen;\n"
    "  let wave_normal = normalize(vec3<f32>(-slope.x, 1.0, -slope.y));\n"
    "  let wave_mix = 0.72 * (1.0 - frozen) * max(input.normal.y, 0.0);\n"
    "  let normal = normalize(mix(input.normal, wave_normal, wave_mix));\n"
    "  let view = normalize(uniforms.camera_pos.xyz - input.world_pos);\n"
    "  let ndotv = max(dot(normal, view), 0.0);\n"
    "  let fresnel = fresnel_schlick(ndotv);\n"
    "  let reflection_dir = reflect(-view, normal);\n"
    "  let reflected = textureSampleLevel(\n"
    "    ibl_prefiltered_env, ibl_sampler, reflection_dir, 0.55).rgb;\n"
    "  let dimensions = vec2<f32>(textureDimensions(opaque_scene));\n"
    "  let scene_uv = clamp(\n"
    "    input.pos.xy / dimensions,\n"
    "    vec2<f32>(0.001), vec2<f32>(0.999));\n"
    "  let screen_uv = clamp(\n"
    "    scene_uv + normal.xz * (0.018 * (1.0 - fresnel)),\n"
    "    vec2<f32>(0.001), vec2<f32>(0.999));\n"
    "  let scene_color = textureSampleLevel(\n"
    "    opaque_scene, ibl_sampler, scene_uv, 0.0).rgb;\n"
    "  let behind = textureSampleLevel(\n"
    "    opaque_scene, ibl_sampler, screen_uv, 0.0).rgb;\n"
    "  let deep_color = vec3<f32>(0.006, 0.075, 0.125);\n"
    "  let shallow_color = vec3<f32>(0.025, 0.22, 0.28);\n"
    "  let water_depth = max(input.terrain_depth, 0.0);\n"
    "  let depth_mix = smoothstep(0.0, 8.0, water_depth);\n"
    "  let facing = pow(1.0 - ndotv, 1.5);\n"
    "  let absorption = clamp(0.08 + depth_mix * 0.72 + facing * 0.2, 0.0, 1.0);\n"
    "  let refracted = mix(behind * shallow_color * 1.65, deep_color, absorption);\n"
    "  let light = normalize(-uniforms.light_ray_dir.xyz);\n"
    "  let half_vector = normalize(view + light);\n"
    "  let sun = pow(max(dot(normal, half_vector), 0.0), 420.0)\n"
    "    * max(dot(normal, light), 0.0);\n"
    "  let ambient = textureSampleLevel(\n"
    "    ibl_irradiance_env, ibl_sampler, normal, 0.0).rgb;\n"
    "  let water_color = mix(shallow_color, deep_color, depth_mix);\n"
    "  let body = refracted + ambient * water_color * 0.35;\n"
    "  let color = mix(body, reflected, clamp(fresnel * 1.15, 0.0, 1.0))\n"
    "    + uniforms.light_color.rgb * sun * 2.2;\n"
    "  let ice_pattern = 0.5 + 0.5\n"
    "    * sin(p.x * 0.47 + sin(p.y * 0.31))\n"
    "    * sin(p.y * 0.41 + sin(p.x * 0.23));\n"
    "  let ice_base = vec3<f32>(0.56, 0.72, 0.79)\n"
    "    + vec3<f32>(ice_pattern * 0.08);\n"
    "  let ice_sun = pow(max(dot(normal, half_vector), 0.0), 90.0)\n"
    "    * max(dot(normal, light), 0.0);\n"
    "  let ice_color = mix(ice_base, reflected, 0.32)\n"
    "    + ambient * ice_base * 0.22\n"
    "    + uniforms.light_color.rgb * ice_sun * 0.8;\n"
    "  let surface_color = mix(color, ice_color, frozen);\n"
    "  let water_visibility = smoothstep(0.0, 1.5, input.terrain_depth);\n"
    "  let ice_visibility = smoothstep(0.0, 1.0, input.terrain_depth);\n"
    "  let visibility = mix(water_visibility, ice_visibility, frozen);\n"
    "  return vec4<f32>(mix(scene_color, surface_color, visibility), 1.0);\n"
    "}\n";

#endif
